---
- name: Let's copy our executable script to remote location, execute script and get result back.
  remote_user: root
  hosts: appserver1
  tasks:
     - name: Execute the script
       command: sh /opt/IBM/WebSphere/AppServer_1/profiles/Dmgr01/bin/startManager.sh
